In [4]:
import pandas as pd
file = "UNCLEANED_voter_data.csv"
voter_data = pd.read_csv(file)
voter_data = voter_data.iloc[:,:11]
voter_data.head()
voter_data = voter_data.dropna()
voter_data.head()

,Year,ICPSR State Code,Alphanumeric State Code,State,VEP Total Ballots Counted,VEP Highest Office,VAP Highest Office,Total Ballots Counted (Estimate),Highest Office,Voting-Eligible Population (VEP),Voting-Age Population (VAP)
0,2016,0,0,United States,0.601,0.592,0.547,138846571.0,136753936.0,230931921,250055734
1,2016,41,1,Alabama,0.591,0.588,0.563,2134061.0,2123372.0,3609447,3770142
2,2016,81,2,Alaska,0.615,0.610,0.574,321271.0,318608.0,522679,555367
3,2016,61,3,Arizona,0.561,0.549,0.489,2661497.0,2604657.0,4740310,5331034
4,2016,42,4,Arkansas,0.532,0.528,0.494,1137772.0,1130635.0,2140097,2286625

In [5]:
voter_data.to_csv("voter_data.csv",encoding="utf-8",index=False)